window.WAKWA_SERVICES = [
 {slug:"construction-haulage",icon:"🏗️",title:"Construction Materials Haulage",short:"Sand, ballast, hardcore & stone delivered fast.",body:"We haul sand, ballast, hardcore, murram, quarry stone, cement, blocks, pavers, steel, timber and roofing sheets from source to site. Tippers from 7T to 30T, trailers for bulk pushes, and off-road capable units for remote plots. We schedule around your fundi and pour days so material lands exactly when needed.",included:["7T–30T tippers + trailers","Quarry pickup + delivery","Timed pour-day scheduling","Off-road / remote access"],ideal:"Contractors, developers, hardware stores, homeowners building.",fleet:["tipper7","tipper10","tipper20","tipper30"],faqs:[["Minimum load?","One 7T tipper is our minimum in town; up-country we combine loads."]]},
 {slug:"bulk-supply",icon:"🧱",title:"Bulk Materials Supply & Sourcing",short:"One invoice, one partner — sourced & delivered.",body:"We source genuine river sand, ballast, hardcore, murram, cement, steel and more from vetted quarries and factories, then deliver to your doorstep. One quote, one invoice, one accountable partner. Send your BOQ and we price the full materials schedule.",included:["Vetted quarries & suppliers","BOQ pricing in 24h","Staged deliveries","Quality checks on arrival"],ideal:"Developers, contractors, NGOs, homeowners.",fleet:["tipper10","tipper20"],faqs:[["Do you sell without transport?","Yes — ex-quarry supply can be arranged, but delivered pricing is usually cheaper."]]},
 {slug:"longhaul-crossborder",icon:"🛣️",title:"Long-Haul & Cross-Border Freight",short:"Nationwide + regional corridors, cleared.",body:"Door-to-door linehaul across the country and into neighbouring regional corridors. We handle route planning, permits, axle-load compliance, driver relays and border paperwork support so your cargo keeps moving day and night.",included:["FTL & part-loads","Border documentation support","GPS tracking +POD","Night-running crews"],ideal:"Manufacturers, distributors, humanitarian programs.",fleet:["flatbed","box"],faqs:[["Which documents?","Commercial invoice, packing list, permits; we give you a checklist per corridor."]]},
 {slug:"tipper-services",icon:"🚚",title:"Tipper / Dump Truck Services",short:"Hourly, daily or per-load tippers.",body:"Tipper hire by the load, day, week or month. 7T for tight urban plots, 10T all-rounders, 20–30T for bulk earthworks. Hourly hire for site shuttle, per-load for supply. Drivers experienced in tipping on uneven ground.",included:["7T/10T/20T/30T options","Wet & dry hire","Site shuttle rates"],ideal:"Earthworks, roadworks, quarries.",fleet:["tipper7","tipper10","tipper20","tipper30"],faqs:[]},
 {slug:"lowbed-machinery",icon:"🚜",title:"Low-Bed & Heavy Machinery Transport",short:"Excavators, graders, rollers moved safely.",body:"Low-beds and low-loaders for excavators, loaders, graders, rollers, cranes and plant. We check dimensions, weight, permits, escorts and route obstacles (bridges, power lines) before dispatch. Ramps, winches and lashing included.",included:["20–60T low-beds","Route survey","Escorts + permits","Loading/unloading support"],ideal:"Contractors, quarries, plant hirers.",fleet:["lowbed"],faqs:[]},
 {slug:"container-port",icon:"📦",title:"Container & Port Clearing Logistics",short:"20ft/40ft + last-mile delivery.",body:"Port pickup, clearance support, and delivery of 20ft and 40ft containers — full or empty. Skeletal trailers, flatbeds and side-loaders coordinated with your clearing agent. Return of empties managed.",included:["Port pickup slots","Agent coordination","Empty returns"],ideal:"Importers, distributors.",fleet:["flatbed"],faqs:[]},
 {slug:"water-bowser",icon:"💧",title:"Water Bowser & Liquid Transport",short:"Clean water bowsers, fast.",body:"Food-grade and construction water bowsers from 5,000L to 20,000L for sites, events, homes and emergency supply. Scheduled refill contracts available.",included:["5k–20k litres","Scheduled refills","Emergency runs"],ideal:"Sites, events, institutions.",fleet:["tanker"],faqs:[]},
 {slug:"fuel-hazmat",icon:"⛽",title:"Fuel & Hazardous Goods",short:"ADR-style handling, trained crew.",body:"Fuel, lubricants and packaged hazardous goods moved with trained drivers, spill kits, placarding and route controls. Strict no-night-parking-near-crowds policy and check-in calls.",included:["Trained hazmat drivers","Spill kits + PPE","Route risk checks"],ideal:"Petrol stations, factories, mines.",fleet:["tanker"],faqs:[]},
 {slug:"agri-produce",icon:"🌾",title:"Agricultural & Produce Transport",short:"Farm to market without bruising.",body:"Grain, potatoes, onions, animal feeds, fertiliser and inputs moved with tarpaulins, nets and careful stacking. Seasonal contracts for harvest peaks.",included:["Tarped + netted loads","Up-country collection","Market delivery slots"],ideal:"Farmers, aggregators, agri-business.",fleet:["box","flatbed"],faqs:[]},
 {slug:"coldchain",icon:"❄️",title:"Cold-Chain / Perishables (On Request)",short:"Refrigerated units on request.",body:"Refrigerated transport for meat, dairy, fish, flowers and vaccines — on request and subject to unit availability. Pre-cooled loading and temperature logs provided.",included:["Reefer units","Temp monitoring","Priority dispatch"],ideal:"Processors, exporters, pharma.",fleet:["reefer"],faqs:[["Lead time?","Book 72h ahead; reefers are limited."]]},
 {slug:"warehousing-3pl",icon:"🏬",title:"Warehousing, Distribution & 3PL",short:"Store, pick, pack, dispatch.",body:"Short-term staging, cross-dock, pick-and-pack and scheduled distribution for FMCG and building products. Shared and dedicated runs.",included:["Staging space","Scheduled routes","Stock reports"],ideal:"Manufacturers, FMCG.",fleet:["box","van"],faqs:[]},
 {slug:"relocation",icon:"🏠",title:"Relocation & Office Moves",short:"Careful household & office moves.",body:"Household and office moves with wrapping, dismantling, loading crews and next-day reassembly. Inventory list and goods-in-transit cover on request.",included:["Crews + wrapping","Furniture handling","Inter-town moves"],ideal:"Families, offices, institutions.",fleet:["box","van"],faqs:[]},
 {slug:"waste-debris",icon:"♻️",title:"Waste, Debris & Site Clearance",short:"Skip loads out, clean site back.",body:"Rubble, excavated soil, demolished material and site waste cleared with tippers and skip loaders. Responsible tipping at approved sites.",included:["Skip + tipper clearance","Approved disposal","Final sweep option"],ideal:"Contractors, renovations.",fleet:["skip","tipper10"],faqs:[]},
 {slug:"abnormal-loads",icon:"⚠️",title:"Project & Abnormal Load Logistics",short:"Oversize loads, engineered moves.",body:"Beams, tanks, transformers, prefab units and abnormal loads with route surveys, permits, escorts, night moves and lifting coordination.",included:["Surveys + permits","Escort vehicles","Lift planning"],ideal:"Energy, construction, industry.",fleet:["lowbed","flatbed"],faqs:[]}
];
